// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:43e9772c-d526-4df8-bd77-2f4428f313c4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ByeLpZjlf",
    "aws_user_pools_web_client_id": "1809ccqhbgl5m0d5lqudkmm1r1",
    "oauth": {
        "domain": "tetrabodyedadeb21-edadeb21-tetra.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/--/",
        "redirectSignOut": "exp://127.0.0.1:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
